name: CI
on: [push, pull_request]
jobs:
  test:
    name: Node ${{ matrix.node }}, Mongo ${{ matrix.mongodb-version }}, on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['12', '14', '16']
        mongodb-version: [3.6, 4.0, 4.2, 4.4, 5.0]
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      
      # ignoring scripts to not install mongodb-memory-server
      - run: npm install --ignore-scripts 

      - run: npm run ci
        env:
          CI: true
